### ISSUE TITLE
ReadMe needs instructions

### ISSUE THREAD

**Issue by airbr** [sfreeman422/RaspAlarm#1]
Cool project ! 
BUT perhaps needs some more instructions to how to get started.

-I Cloned repo to Rasp Pi with touchscreen running 
-NPM Installed in root of the repo
-(Mongo is installed on Raspberry Pi)
-Did `node server.js in the root`
-Something is appeared to be served at localhost:3000 but as far yet its a black screen. 
- Realized I needed to use webpack in root where config is

Got this:

```
pi@raspberrypi:~/Documents/RaspAlarm $ webpack
Hash: 37ee781105d39d10c02e
Version: webpack 1.14.0
Time: 29708ms
           Asset     Size  Chunks             Chunk Names
public/bundle.js  1.39 MB       0  [emitted]  main
    + 357 hidden modules

ERROR in ./app/components/Main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../../private/keys.js in /home/pi/Documents/RaspAlarm/app/components
 @ ./app/components/Main.js 16:11-43

```

Just attempting to be helpful, I had my touchscreen sitting around this is a great project to put it to use.
 

Regards

**Comment by sfreeman422** [comment]
Hey there, you would need to set up a folder called private with a file called keys.js. Inside of that you would need to include 

```
var keys = KEYFROMWEATHERUNDERGROUNDAPI

module.exports = keys; 
```
You should then be able to use the app as expected. I plan to update the readme sometime this week with detailed instructions on how to get this up and running. If you need to request a Weather Underground API key, hit this link: https://www.wunderground.com/weather/api/

**Comment by sfreeman422** [comment]
Updated the readme to include step by step instructions to get set up with weatherunderground api and begin using the repo.
